name: QrScanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  image_gallery_saver: ^1.1.0
  image_picker: ^0.6.1+4
  permission_handler: ^5.0.1+1
  qrscan: ^0.2.22

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - images/generate_qrcode.png
    - images/scanner.png
    - images/albums.png
